config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "entries#index"

  resources :entries
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user

  def proper_owner?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :entries
  enum role: [:user, :admin]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  def user_not_authorized
    redirect_to(request.referrer || root_path, alert: 'Not autorized')
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :find_entry, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def index
    @entries = Entry.all
  end

  def show
    authorize @entry
  end

  def new
    @entry = Entry.new
    authorize @entry
  end

  def create
    @entry = Entry.new(entry_params)
    authorize @entry
    @entry.user = current_user
    if @entry.save
      redirect_to entries_path, notice: 'Entry created'
    else
      redirect_to entries_path, alert: 'Error while creating entry'
    end
  end

  def edit
    authorize @entry
  end

  def update
    authorize @entry
    if @entry.update_attributes(entry_params)
      redirect_to entries_path, notice: 'Entry, updated'
    else
      redirect_to entries_path, alert: 'Error while updating entry'
    end
  end

  def destroy
    authorize @entry
    @entry.destroy
    redirect_to entries_path, notice: 'Entry deleted'
  end

  private

  def find_entry
    @entry = Entry.find(params[:id])
  end

  def entry_params
    params.require(:entry).permit(:title, :content, :published)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/entries/edit.html.haml
=form_for @entry, path: entry_path, method: :patch do |f|
  =f.label :title
  =f.text_field :title
  =f.label :content
  =f.text_area :content
  =f.label :published
  =f.check_box :published
  =f.submit 'submit'

app/views/entries/index.html.haml
-if current_user
  =link_to 'Add new entry', new_entry_path
%ol
  -@entries.each do |entry|
    %li
      %ul
        %li
          %h4
            =entry.title
        %li
          =entry.user.email
        %li
          %p
            =entry.content
        %li
          =link_to 'show', entry_path(entry)

app/views/entries/new.html.haml
=form_for @entry do |f|
  =f.label :title
  =f.text_field :label
  =f.label :content
  =f.text_area :content
  =f.label :published
  =f.check_box :published
  =f.submit 'submit'

app/views/entries/show.html.haml
=link_to 'Edit this entry', edit_entry_path(@entry)
=link_to 'Delete this entry', entry_path(@entry), method: :delete
%h2
  =@entry.title
%p
  =@entry.user.email
%p
  =@entry.content

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title RailsWithPundit
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    - if user_signed_in?
      %p.navbar-text
        Signed in, #{current_user.email}
    %ul.nav.nav-pills.navbar-right
      - if user_signed_in?
        %li= link_to "Sign out", destroy_user_session_path, method: :delete
      - else
        %li= link_to "Sign in", new_user_session_path
        %li= link_to "Sign up", new_user_registration_path
    %p.notice= notice
    %p.alert= alert
    = yield